services:
  autowaterer-db:
    build:
      context: ./
      dockerfile: src/server/Dockerfile.db
    container_name: autowaterer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - autowaterer_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  autowaterer-api:
    build:
      context: ./
      dockerfile: src/server/Dockerfile
    container_name: autowaterer-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_HOST: autowaterer-db
    depends_on:
      autowaterer-db:
        condition: service_healthy

  autowaterer-ui:
    build:
      context: ./
      dockerfile: src/app/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://toth-server.local:${API_PORT:-3001}
    container_name: autowaterer-ui
    restart: unless-stopped
    depends_on:
      - autowaterer-api
    env_file:
      - .env

volumes:
  autowaterer_postgres_data: