services:
  postgres:
    image: postgres:16-alpine
    container_name: autowaterer-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/server/persistence/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    env_file:
      - .env

  express:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    container_name: autowaterer-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - postgres

  nextjs:
    build:
      context: ./
      dockerfile: src/app/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://toth-server.local:3001
    container_name: autowaterer-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - express
    env_file:
      - .env

volumes:
  postgres_data: